# Generated by Django 6.0.3 on 2026-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cleaning', '🧹 Cleaning'), ('groceries', '🛒 Groceries'), ('transport', '🚗 Transport'), ('tech', '💻 Tech Help'), ('gardening', '🌿 Gardening'), ('cooking', '🍲 Cooking'), ('other', '✨ Other')], max_length=50)),
                ('offer_type', models.CharField(choices=[('paid', 'Paid'), ('volunteer', 'Volunteer')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
