# Generated by Django 6.0.3 on 2026-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
