# Generated by Django 6.0.3 on 2026-03-26 11:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offers', '0002_offer_contact_info'),
    ]

    # User model was moved to `0001_initial` so `admin` can resolve AUTH_USER_MODEL early.
    operations = []
