# Generated by Django 6.0.3 on 2026-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_accepted_at_offer_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('completed', 'Done')], db_index=True, default='waiting', max_length=20),
        ),
    ]
