# Generated by Django 6.0.3 on 2026-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('cleaning', '🧹 Чистене'), ('groceries', '🛒 Пазаруване'), ('transport', '🚗 Транспорт'), ('tech', '💻 Помощ с техника'), ('gardening', '🌿 Помощ с градината'), ('cooking', '🍲 Готвене'), ('other', '✨ Друго')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Доброволец/Работник'), ('needer', 'Търсещ помощ')], default='needer', max_length=10),
        ),
    ]
