# Generated by Django 6.0.3 on 2026-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offer_category_alter_user_user_type'),
        ('offers', '0009_alter_offer_category_alter_user_user_type_and_more'),
    ]

    operations = [
    ]
